### ISSUE TITLE
Create a WikiPage with an example

### ISSUE THREAD

**Issue by Heinerion** [c0bra/markdown-resume-js#10]
I'd like to use this project for my resume, but the [example](https://raw.githubusercontent.com/there4/markdown-resume/master/examples/source/sample.md) of the [there4 blog](http://there4.io/2012/12/31/markdown-resume-builder/) doesn't produce the desired result. 

E.g: I get `Profile {#profile}` as headings instead of the proper ones

I'd love to see an example in the wiki pages or possibly in the sources.  
Thanks for your efforts!

**Comment by ldumaine** [comment]
An example is available in the sources:
[https://github.com/c0bra/markdown-resume-js/raw/master/test/fixtures/resume.md](https://github.com/c0bra/markdown-resume-js/raw/master/test/fixtures/resume.md)

**Comment by Heinerion** [comment]
Thank you very much! I will try it shortly.

**Comment by jingxlim** [comment]
Hey guys, also wondering what this looks like. What are the main differences between this and Craig Davis' Markdown Resume Generator, which this borrows from?

**Comment by c0bra** [comment]
@jingxlim This one's written in node.js. Craig's is PHP. That's mostly it. His might be more up to date as well.
