### ISSUE TITLE
#footer no longer <h1 id="footer">footer</h1>

### ISSUE THREAD

**Issue by defkev** [c0bra/markdown-resume-js#11]
Just redeployed on another box and noticed that the #footer tag no longer works as intended.

**in.md**
`#footer`

**out.html**
`<p>#footer</p>`
instead of
`<h1 id="footer">footer</h1>`

**Comment by defkev** [comment]
Functionality got lost somewhere in between marked 0.3.3 and 0.3.5

**Comment by c0bra** [comment]
Looks like you need a space after the hash: `# footer`
