### ISSUE TITLE
Image not displayed when converted into pdf. 

### ISSUE THREAD

**Issue by DrSensor** [c0bra/markdown-resume-js#16]
Related to #15, the image is not displayed when converted to pdf. 
I suggest in the codes make all img urls into base64 when converted into html.

**Comment by c0bra** [comment]
@DrSensor will take a look

**Comment by c0bra** [comment]
@DrSensor give it a shot with version 2.1.0. It should work

**Comment by c0bra** [comment]
Closing as images now get brought in by `inliner`
