### ISSUE TITLE
Interested in refactoring?

### ISSUE THREAD

**Issue by dremonkey** [c0bra/markdown-resume-js#4]
The php version of markdown-resume allows for separate templates (as directories) rather than as a single file. This version does not, so I forked and refactored to allow for this. 

Additionally, I got rid of stylus and sqwish and replaced it with pure less.

The expected template layout is a bit different than the php version, but it takes very little work to adapt them to work.

Would you be interested in merging these changes with your project? You can check out my branch here: https://github.com/dremonkey/markdown-resume-js/tree/refactored

Usage is basically the same except that the -t option points to a directory now rather than a file, i.e. ```node bin/md2resume test/resume.md -t templates/modern```

**Comment by JaKXz** [comment]
+1 for sure!

**Comment by c0bra** [comment]
Done via @JaKXz  PR
